//
//  Levels.swift
//  Phish Finder
//
//  Created by Ethan Ondreicka on 2/11/25.
//

// File to store all levels because this could get really long lol

let levels: [Level] = [
    
    // Tutorial Level
    Level(emailText: "Claim your free prize now!",isFishing: true,toEmail: "user@example.com", fromEmail: "giveaways@pāypal.com",levelNumber: 0, subjectLine: "Congratulations, You’ve Won!", emailLink: "http://clickhereforscam.com", explanation: "This email promises a prize and includes a suspicious link.",difficulty: .tutorial),
    
    // Easy Levels
        Level(emailText: "Hello my friend!\n\n I recently inherited lots of money after my father passed away. Click here to claim your share!", isFishing: true, toEmail: "my_email@me.com", fromEmail: "73497ds349234@mail.com", levelNumber: 1, subjectLine: "Urgent: Free Money!", emailLink: "https://www.monay-fre3.com/claim", explanation: "Weird domain name and accents are suspicious.", difficulty: .easy),
        Level(emailText: "Congratulations! You've won a free iPhone 15! Click the link below to claim your prize before it expires.", isFishing: true, toEmail: "my_email@me.com", fromEmail: "promo-gìveaway@apple-offers.net", levelNumber: 4, subjectLine: "Claim Your Free iPhone 16 Pro Now!", emailLink: "https://www.appel.com/iphone", explanation: "Too good to be true, classic phishing.", difficulty: .easy),
        Level(emailText: "Hello,\n\nJust a reminder that your dentist appointment is scheduled for next Wednesday at 2 PM.\n\nBest,\nDr. Smith's Office", isFishing: false, toEmail: "my_email@me.com", fromEmail: "appointments@drsmithdental.com", levelNumber: 7, subjectLine: "Upcoming Dentist Appointment", emailLink: "", explanation: "Legitimate appointment reminder.", difficulty: .easy),
        Level(emailText: "Dear customer,\n\nYour Amazon order #45321 has been shipped and will arrive in 3 days.\n\nThanks for shopping with us!", isFishing: false, toEmail: "my_email@me.com", fromEmail: "order-updates@amazon.com", levelNumber: 10, subjectLine: "Your Amazon Order Has Shipped!", emailLink: "", explanation: "Legitimate confirmation from Amazon.", difficulty: .easy),
        Level(emailText: "Your account has been compromised. Verify your password immediately by clicking this link.", isFishing: true, toEmail: "my_email@me.com", fromEmail: "secur1ty-alert@paypäl.com", levelNumber: 2, subjectLine: "Security Alert: Account Compromised", emailLink: "https://www.paypäl.com/verify", explanation: "Misspelled sender name and urgent language.", difficulty: .easy),
        Level(emailText: "Free gift card! Click here to claim $50 at Walmart!", isFishing: true, toEmail: "my_email@me.com", fromEmail: "offers@wãlmart-deals.com", levelNumber: 15, subjectLine: "Claim Your Reward!", emailLink: "https://www.walmrt.com/giveaways", explanation: "Obvious prize scam.", difficulty: .easy),
        Level(emailText: "You’ve been selected for a free vacation! Click below to reserve your spot!", isFishing: true, toEmail: "my_email@me.com", fromEmail: "travel@wìn-vacatìon.com", levelNumber: 17, subjectLine: "Free Vacation Awaits!", emailLink: "https://www.vacatìon.com/free", explanation: "Unsolicited prize offers are a red flag.", difficulty: .easy),
        Level(emailText: "Hi,\n\nYour package delivery is scheduled for tomorrow between 10 AM and 2 PM.\n\nThanks,\nUPS Team", isFishing: false, toEmail: "my_email@me.com", fromEmail: "tracking@ups.com", levelNumber: 18, subjectLine: "Delivery Scheduled", emailLink: "", explanation: "Legitimate shipping notification.", difficulty: .easy),
        Level(emailText: "Click here to get a $100 coupon for your next purchase!", isFishing: true, toEmail: "my_email@me.com", fromEmail: "deals@shòp-now.com", levelNumber: 19, subjectLine: "Exclusive Offer Just for You!", emailLink: "https://www.shoppìng.com/coupon", explanation: "Unrealistic offers often lead to scams.", difficulty: .easy),
        
        // Medium Levels
        Level(emailText: "Your tax refund is ready. Click here to confirm your banking details and receive your refund immediately.", isFishing: true, toEmail: "my_email@me.com", fromEmail: "irs-refund@usgovtaxeś.com", levelNumber: 5, subjectLine: "IRS Tax Refund Notification", emailLink: "https://www.1RS.com/refund", explanation: "Government agencies don’t email for personal info.", difficulty: .medium),
        Level(emailText: "Hi Mom,\n\nCan you send me some money? My phone is broken, and I can't use my regular number.\n\nThanks!", isFishing: true, toEmail: "my_email@me.com", fromEmail: "your-son-realḻy@email.com", levelNumber: 6, subjectLine: "Urgent: Need Help!", emailLink: "", explanation: "Impersonation scam trying to trick you.", difficulty: .medium),
        Level(emailText: "Hey it's Jake from High School, \n\nlooking to hang out sometime soon? I haven't seen you in so long! \n\n\nRegards,\nJake", isFishing: false, toEmail: "my_email@me.com", fromEmail: "jake.smith@email.com", levelNumber: 3, subjectLine: "Long time no see!", emailLink: "", explanation: "Legit sender, no scam.", difficulty: .medium),
        Level(emailText: "Reminder: Your gym membership renewal is due next week. Let us know if you need any changes.\n\nBest,\nYour Gym", isFishing: false, toEmail: "my_email@me.com", fromEmail: "support@fitnessplus.com", levelNumber: 13, subjectLine: "Membership Renewal Notice", emailLink: "", explanation: "Legitimate reminder from a gym.", difficulty: .medium),
        Level(emailText: "Your Netflix account will be suspended today due to payment failure. Update your billing info now to continue streaming.", isFishing: true, toEmail: "my_email@me.com", fromEmail: "support@netflìx-bílling.com", levelNumber: 11, subjectLine: "Netflix Payment Failed!", emailLink: "https://www.example.com/netflix", explanation: "Fake Netflix billing alert.", difficulty: .medium),
        Level(emailText: "Dear Client,\n\nYour recent payment was declined. Please update your card details to avoid service interruption.", isFishing: true, toEmail: "my_email@me.com", fromEmail: "billing@spòtify-support.com", levelNumber: 20, subjectLine: "Payment Declined Notice", emailLink: "https://www.spòtify.com/update", explanation: "Subtle misspelling in domain name.", difficulty: .medium),
        Level(emailText: "Hi,\n\nYour subscription to our newsletter has been confirmed. Unsubscribe anytime if needed.\n\nBest,\nTechBlog Team", isFishing: false, toEmail: "my_email@me.com", fromEmail: "news@techblog.com", levelNumber: 21, subjectLine: "Welcome to TechBlog!", emailLink: "", explanation: "Legitimate subscription confirmation.", difficulty: .medium),
        Level(emailText: "Your account login was detected from a new device. Verify it was you by clicking here.", isFishing: true, toEmail: "my_email@me.com", fromEmail: "security@gmaìl-secure.com", levelNumber: 22, subjectLine: "New Device Login Alert", emailLink: "https://www.gmaìl.com/verify", explanation: "Fake Google alert with odd characters.", difficulty: .medium),
        
        // Hard Levels
        Level(emailText: "We noticed suspicious activity on your PayPal account. Click the link below to secure your account now.", isFishing: true, toEmail: "my_email@me.com", fromEmail: "servíces@páypal-secure.com", levelNumber: 8, subjectLine: "Urgent: PayPal Account Suspended", emailLink: "https://www.páypal.com/reset-password", explanation: "Fake domain trying to look like PayPal.", difficulty: .hard),
        Level(emailText: "Hey,\n\nI found an old photo of us from college! Check it out here: [link].\n\nHope you're doing well!", isFishing: true, toEmail: "my_email@me.com", fromEmail: "memories@oldphòtó-sharé.com", levelNumber: 9, subjectLine: "Look at this photo!", emailLink: "https://www.example.com/photo", explanation: "Random email with a link is suspicious.", difficulty: .hard),
        Level(emailText: "Hey,\n\nCan you review this document for me? It's really important.\n\nThanks!", isFishing: true, toEmail: "my_email@me.com", fromEmail: "boss@worḳ-docs.com", levelNumber: 12, subjectLine: "Quick Favor: Check This Document", emailLink: "7437439409179.pdf", explanation: "Malicious attachments are a phishing trick.", difficulty: .hard),
        Level(emailText: "URGENT: Your bank account is at risk! Click below to confirm your details before your funds are frozen.", isFishing: true, toEmail: "toemail@mail.com", fromEmail: "alerts@chãse-bánk-secure.com", levelNumber: 14, subjectLine: "Bank Fraud Alert", emailLink: "https://www.chasę-bánk.com/bank", explanation: "Banks don’t request sensitive info via email.", difficulty: .hard),
        Level(emailText: "Team,\n\nPlease update your payroll info by tomorrow using this link.\n\nHR Dept", isFishing: true, toEmail: "my_email@me.com", fromEmail: "hr@compãny-payroll.com", levelNumber: 16, subjectLine: "Payroll Update Required", emailLink: "https://www.example.com/payroll", explanation: "Subtle fake domain mimicking company email.", difficulty: .hard),
        Level(emailText: "Hi,\n\nWe’ve processed your recent request for a loan. View the terms here before signing.", isFishing: true, toEmail: "toemail@mail.com", fromEmail: "loans@wélls-fargò.com", levelNumber: 23, subjectLine: "Loan Approval Details", emailLink: "https://www.wélls-fargò.com/terms", explanation: "Sophisticated fake domain mimicking a bank.", difficulty: .hard),
        Level(emailText: "Dear Employee,\n\nYour quarterly performance review is ready. Please download it here.\n\nRegards,\nManagement", isFishing: true, toEmail: "my_email@me.com", fromEmail: "reviews@mycompañy-hr.com", levelNumber: 24, subjectLine: "Performance Review Available", emailLink: "performance_review_2025.pdf", explanation: "Subtle domain tweak hides a phishing attempt.", difficulty: .hard),
        Level(emailText: "Your recent transaction was flagged for review. Confirm it was you by clicking here.", isFishing: true, toEmail: "my_email@me.com", fromEmail: "fraud@bànk-of-américa.com", levelNumber: 25, subjectLine: "Transaction Verification Needed", emailLink: "https://www.bànk-of-américa.com/confirm", explanation: "Cleverly disguised domain with urgent tone.", difficulty: .hard),
        Level(emailText: "Team,\n\nDue to a system upgrade, all employees must reset their passwords by EOD today. Use this link to proceed.\n\nIT Dept", isFishing: false, toEmail: "my_email@me.com", fromEmail: "it@company.com", levelNumber: 26, subjectLine: "Mandatory Password Reset Today", emailLink: "https://intranet.company.com/reset", explanation: "Urgent tone and link might seem fishy, but it’s a legit internal IT request.", difficulty: .hard),
    Level(emailText: "Hi,\n\nYour recent support ticket (#78912) has an update. Download the resolution details here.\n\nBest,\nSupport Team", isFishing: false, toEmail: "my_email@me.com", fromEmail: "support@softwareco.com", levelNumber: 27, subjectLine: "Support Ticket #78912 Update", emailLink: "ticket_78912_resolution.pdf", explanation: "Attachment could raise suspicion, but it’s a genuine support response.", difficulty: .hard)
]





